### ISSUE TITLE
SDK LTS_07_2022 Migration - Issue with TPM - Endian Agnostic ?

### ISSUE THREAD

**Issue by neonsoftware** [Azure/azure-utpm-c#113]
Hi.

### Issue

We have attempted migrate the C SDK as follows:
**LTS_07_2021** --to--> **LTS_07_2022**
but encountered runtime errors on UTPM.

### Device Information

* OpenWRT 21
* MIPS 32 24k big endian
* Provisioning Method: TPM

### On Endianness

One main aspect of this migration had been the following:

- since the beginning of our codebase, there has always been an inherited patch to utpm, [here gist of the patch](https://gist.github.com/neonsoftware/b44b36fa2706c7b8ef69040659e37098), that was marked as acting on the endianness
- the patch had always appllied smoothly up to LTS_07_2021, then breaking when moving to LTS_07_2022
- a short test with LTS_07_2022, without such patch, had failed on tpm issues, but I do not have logs for the moment. 

### Question

- Is being endian agnostic a constraint for the UTPM and SDK project, and if yes are there tests in place ?
- Should we provide tests/logs for this issue ?

Thank you in advance

**Comment by ewertons** [comment]
Hi @neonsoftware ,
I verified the code and there were no changes (from LTS_07_2021 to LTS_07_2022) to the files affected by your git patch.

Since there no changes, I would expect the functionality to be the same from our codebase perspective.

```bash
pi@pi4:~/code/azure-iot-sdk-c/provisioning_client/deps/utpm $ git log -n 2 1d0642281086669c6239f9bc1b085463044d69d6..3f1603ded51e4f34106b390af3616dd1f9357aca .
commit c416836e2f629bbf1f0cd59b98fce5229d5f420c
Author: Dane Walton <dawalton@microsoft.com>
Date:   Thu Aug 4 13:45:13 2022 -0700

    Update submodules

commit ffa1f938214aff1defc96fe60c683e212e593de0
Author: Valerie Avva Lim <vaavva@microsoft.com>
Date:   Thu May 12 15:10:11 2022 -0700

    Update submodules
pi@pi4:~/code/azure-iot-sdk-c/provisioning_client/deps/utpm $ git log -n 2 1d0642281086669c6239f9bc1b085463044d69d6..3f1603ded51e4f34106b390af3616dd1f9357aca inc/azure_utpm_c/TpmTypes.h
pi@pi4:~/code/azure-iot-sdk-c/provisioning_client/deps/utpm $ git log -n 2 1d0642281086669c6239f9bc1b085463044d69d6..3f1603ded51e4f34106b390af3616dd1f9357aca src/tpm_codec.c
```

Could you double verify if there were any other changes in your code that could have caused a tpm issue?
If you still believe the issue would be related to this library, could you please share detailed steps of how to repro this issue? Also, which hardware did you use?

**Comment by neonsoftware** [comment]
@ewertons Thank you for checking.
I will re-execute a migration in the beginning of next week and let you know with further information.
Thanks.

**Comment by ewertons** [comment]
Thank you @neonsoftware , I'll me monitoring any updates from you.
