### ISSUE TITLE
Missing information about migration from azure-utpm-c to tss2 with openssl

### ISSUE THREAD

**Issue by tomoveu** [Azure/azure-utpm-c#120]
I could not find any point of contact thus I am opening this ticket in hope we establish communication - I am the founder of the largest [TPM developers community](https://tpm.dev) and my hope is that we can host someone from the Microsoft team to explain us in technical detail how this migration actually happens in Azure for existing TPM adopters. 

We are a group of over 500 developers who use HSM and especially TPM on a daily basis. Please engage with us and let's arrange some talk in september or october. My primary email is listed on my github profile.

Thanks,
Dimi
/Founder of TPM.dev

**Comment by CIPop** [comment]
@tomoveu, as mentioned in the announcement, existing applications will continue to work as-is. There are no plans to disable the DPS-TPM protocol support on the service side or to remove the functionality from C-SDK.

Applications may choose to switch to the DPS-X509 where we recommend HSM-backed private keys. In particular, for Linux / OpenSSL / TPMv2 capable devices:
1. Use the OpenSSL TPM2TSS Engine: usage instructions available at the [tpm2tss OpenSSL project repo](https://github.com/tpm2-software/tpm2-tss-engine#usage). 
2. After tpm2tss has been configured correctly with an X.509 certificate and TPM-backed key, see the [C-SDK OpenSSL Engine instructions](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/devdoc/iothubclient_c_library.md#openssl-engine-examples)

**Comment by tomoveu** [comment]
@CIPop  Thank you for the details. I am closing this issue.
